In [1]:
from getpass import getpass
from dotenv import load_dotenv
import pandas as pd
import requests
import os
import folium
import pandas as pd

In [2]:
load_dotenv()

True

In [3]:
token = os.getenv("token")

In [4]:
df_sanfrancisco = pd.read_csv("../dataframes/df_sanfrancisco.csv")
df_london = pd.read_csv("../dataframes/df_london.csv")
df_newyork = pd.read_csv("../dataframes/df_newyork.csv")

In [5]:
def category_from_foursquare (lon, lat, category):

    url = f"https://api.foursquare.com/v3/places/search?&ll={lon}%2C{lat}&categories={category}&sort=DISTANCE&limit=3"
    
    headers = {
        "accept": "application/json",
        "Authorization": token
    }

    response = requests.get(url, headers=headers).json()
    return response

In [6]:
def query_from_foursquare (query, lon, lat):
    
    url = f"https://api.foursquare.com/v3/places/search?query={query}&ll={lon}%2C{lat}&sort=DISTANCE&limit=3"

    headers = {
        "accept": "application/json",
        "Authorization": token
    }

    response = requests.get(url, headers=headers).json()
    return response

In [7]:
def everything_from_foursquare (one_element, data):

    name = one_element["name"]
    lat = one_element["geocodes"]["main"]["latitude"]
    lon = one_element["geocodes"]["main"]["longitude"]
    distance = one_element["distance"]
    
    dict_ = {"name": name, "latitude": lat, "longitude": lon, "data": data, "distance": distance}
    
    return dict_

In [8]:
sf_lon= "37.7968917"
sf_lat= "-122.4032027"
airport_query="airport"
starbucks_query="Starbucks"
dog_groom_query="Dog grooming"
airport_category= "19040"
preschool_category="12056"
primaryschool_category="12057"
train_category="19046"
nightlife_category="10032"
vegan_category="13377"
basketball_category="18008"

In [9]:
response=category_from_foursquare(sf_lon, sf_lat, airport_category)

In [10]:
new_list = []
for i in response["results"]:
    new_list.append(everything_from_foursquare (i, "Airport"))

df = pd.DataFrame(new_list)
df_sanfrancisco = pd.concat([df_sanfrancisco, df])

In [11]:
response=category_from_foursquare(sf_lon, sf_lat, preschool_category)
new_list = []
for i in response["results"]:
    new_list.append(everything_from_foursquare (i, "Preschool"))

df = pd.DataFrame(new_list)
df_sanfrancisco = pd.concat([df_sanfrancisco, df])

In [12]:
response=category_from_foursquare(sf_lon, sf_lat, primaryschool_category)
new_list = []
for i in response["results"]:
    new_list.append(everything_from_foursquare (i, "Primary and Secondary School"))

df = pd.DataFrame(new_list)
df_sanfrancisco = pd.concat([df_sanfrancisco, df])

In [13]:
response=category_from_foursquare(sf_lon, sf_lat, train_category)
new_list = []
for i in response["results"]:
    new_list.append(everything_from_foursquare (i, "Train Station"))

df = pd.DataFrame(new_list)
df_sanfrancisco = pd.concat([df_sanfrancisco, df])

In [14]:
response=category_from_foursquare(sf_lon, sf_lat, nightlife_category)
new_list = []
for i in response["results"]:
    new_list.append(everything_from_foursquare (i, "Night Club"))

df = pd.DataFrame(new_list)
df_sanfrancisco = pd.concat([df_sanfrancisco, df])

In [15]:
response=category_from_foursquare(sf_lon, sf_lat, vegan_category)
new_list = []
for i in response["results"]:
    new_list.append(everything_from_foursquare (i, "Vegan Restaurant"))

df = pd.DataFrame(new_list)
df_sanfrancisco = pd.concat([df_sanfrancisco, df])

In [16]:
response=category_from_foursquare(sf_lon, sf_lat, basketball_category)
new_list = []
for i in response["results"]:
    new_list.append(everything_from_foursquare (i, "Basketball stadium"))

df = pd.DataFrame(new_list)
df_sanfrancisco = pd.concat([df_sanfrancisco, df])

In [17]:
response=query_from_foursquare (starbucks_query, sf_lon, sf_lat)
new_list = []
for i in response["results"]:
    new_list.append(everything_from_foursquare (i, "starbucks"))

df = pd.DataFrame(new_list)
df_sanfrancisco = pd.concat([df_sanfrancisco, df])

In [18]:
response=query_from_foursquare ( dog_groom_query,sf_lon, sf_lat)
new_list = []
for i in response["results"]:
    new_list.append(everything_from_foursquare (i, "dog grooming"))

df = pd.DataFrame(new_list)
df_sanfrancisco = pd.concat([df_sanfrancisco, df])
df_sanfrancisco

,name,latitude,longitude,data,distance
0,Digg,37.764726,-122.394523,Design company,NaN
1,Wix,37.756720,-122.405070,Design company,NaN
2,99designs,37.795531,-122.400598,Design company,NaN
3,Minted,37.797435,-122.403175,Design company,NaN
4,Netbiscuits,37.755037,-122.426442,Design company,NaN
0,Oakland International Airport (OAK),37.712395,-122.213323,Airport,19161.0
1,San Francisco International Airport (SFO),37.616581,-122.386689,Airport,20067.0
0,Imane's Wonderschool,37.780740,-122.407515,Preschool,1834.0
1,Presidio Knolls School,37.773203,-122.413809,Preschool,2783.0
2,Alta Plaza Preschool,37.790221,-122.437322,Preschool,3138.0
0,Jean Parker Elementary School,37.797687,-122.411024,Primary and Secondary School,693.0
1,New School San Francisco,37.800775,-122.415078,Primary and Secondary School,1125.0
2,Galileo Academy of Science and Technology,37.803767,-122.424217,Primary and Secondary School,2009.0
0,Montgomery St BART Station,37.788862,-122.402116,Train Station,888.0
1,Union Square/Market Street MUNI Metro Station,37.787906,-122.406934,Train Station,1074.0
2,Powell MUNI Metro Station,37.784458,-122.407591,Train Station,1447.0
0,Monroe,37.797885,-122.405014,Night Club,210.0
1,The Saloon,37.798551,-122.406989,Night Club,390.0
2,Pier 23 Cafe,37.803296,-122.400887,Night Club,746.0
0,Enjoy Vegetarian Restaurant,37.795836,-122.405323,Vegan Restaurant,203.0
1,The Lucky Creation Vegetarian Restaurant,37.795217,-122.407437,Vegan Restaurant,411.0
2,The Plant Cafe Organic,37.791658,-122.402281,Vegan Restaurant,559.0
0,Alice Marble Basketball Court,37.801449,-122.420352,Basketball stadium,1580.0
1,Soma Rec Center,37.778838,-122.406328,Basketball stadium,2006.0
2,Berry Basketball Courts,37.772080,-122.397686,Basketball stadium,2814.0
0,Starbucks,37.794601,-122.402669,starbucks,257.0
1,Starbucks,37.795166,-122.400408,starbucks,309.0
2,Starbucks,37.797015,-122.398007,starbucks,453.0
0,Bow Wow Meow,37.796647,-122.421645,dog grooming,1639.0
1,Bernie's Grooming,37.766882,-122.412719,dog grooming,3467.0

In [19]:
df_sanfrancisco.to_csv("../dataframes/df_sanfrancisco.csv", index=False)
df_newyork.to_csv("../dataframes/df_newyork.csv", index=False)
df_london.to_csv("../dataframes/df_london.csv", index=False)